red_box:
  w: 0.07
  l: 0.07
  h: 0.07
  color: "red"
blue_box:
  w: 0.07
  l: 0.07
  h: 0.07
  color: "blue"
green_box:
  w: 0.105
  l: 0.035
  h: 0.07
  color: "green"
tan_box:
  w: 0.035
  l: 0.035
  h: 0.07
  color: "tan"
