cyan_box:
  w: 0.07
  l: 0.07
  h: 0.07
  color: "cyan"
blue_box:
  w: 0.07
  l: 0.07
  h: 0.07
  color: "blue"
red_box:
  w: 0.035
  l: 0.035
  h: 0.04
  color: "red"
yellow_box:
  w: 0.035
  l: 0.035
  h: 0.04
  color: "yellow"